{% set version = "1.5.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tfruns
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tfruns_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tfruns/tfruns_{{ version }}.tar.gz
  sha256: 1cab3346df741623cfdd1b12ade6397d6f28bd1ac57144fc7ab63519460688c7

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-base64enc
    - r-config
    - r-jsonlite >=1.2
    - r-magrittr
    - r-reticulate
    - r-rlang
    - r-rstudioapi >=0.7
    - r-tidyselect
    - r-whisker
    - r-yaml
  run:
    - r-base
    - r-base64enc
    - r-config
    - r-jsonlite >=1.2
    - r-magrittr
    - r-reticulate
    - r-rlang
    - r-rstudioapi >=0.7
    - r-tidyselect
    - r-whisker
    - r-yaml

test:
  commands:
    - $R -e "library('tfruns')"           # [not win]
    - "\"%R%\" -e \"library('tfruns')\""  # [win]

about:
  home: https://github.com/rstudio/tfruns
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: "Create and manage unique directories for each 'TensorFlow'  training run. Provides a unique, time stamped directory for each run along with functions to retrieve the directory of the latest run or  latest several runs. "
  license_family: APACHE

extra:
  recipe-maintainers:
    - conda-forge/r
    - zamorarr
