travis:
  secure:
    BINSTAR_TOKEN: ofOoDLGeCFZusOHk38zc0/UpuyW9AccepFngNRZ0jLZ6B7Ei60yY4BqCPrWCKHzYY1IB+Gh15EdRdbzINsMa2//jV8nVs2Fw6uQZkVmYtm3WmZMsH5v28TtgBB3qm3rMGKEw/a7tB362yPjjipWx47WbwE4kPhHuu84PAKKQ65xBsa4jQE2pq9ST1fwXUP0/n73reWuaBIMXiXk+HhcCY/afIsdc6LG6aaQfXPVZRPl9quDlB6Ji0/H9pK8Sjuw0GBi/y9YGBGDWbSfCqg0dJ/C9xlsDyUvtOHfLWDl7+2EC4k96CkgpSBaA/tUUsgZfPjP7uJLSZM0/yYeusmPQyZsKG0E3bX1/okQkVNsn17eEYMWssOIWRkkDGDdHKX4xK0JzmkxGiTg3ZydHJC8w9PfFYC+8bX0Vl+reMvMnbCykLimZ2ieWeJpXPoeu5QlkWVAMws4oa89PEn7jIwkusyu8iL2CP4/FaPACbl5SgEzzHdIiB1ESyv1+1eXZNkI3rt96ZhyfK2tWT29XHVd9b3BDHn9xsn6VLwmLfXrs85n/JgJExoxyX2Syg34t4BF5J0IikS/kmobLxEG39j/YAlLM/bkP9IR+5WdtizJw4sHJp55pkAmMEzvIUhP8tVd74gm3HwrxxZChZT2MTaC8Ix5Xo+pXULbKZRhfkwshnFM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
